import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    // ── Target: staging deployment ──────────────────────────────────────
    baseUrl: "https://staging-nepay.vercel.app",

    // ── Spec pattern ────────────────────────────────────────────────────
    specPattern: "cypress/e2e/**/*.cy.ts",
    supportFile: "cypress/support/e2e.ts",

    // ── Viewport ────────────────────────────────────────────────────────
    viewportWidth: 1280,
    viewportHeight: 800,

    // ── Timeouts ────────────────────────────────────────────────────────
    defaultCommandTimeout: 30000,
    requestTimeout: 60000,
    responseTimeout: 60000,
    pageLoadTimeout: 60000,

    // ── Retries ─────────────────────────────────────────────────────────
    retries: {
      runMode: 2,   // CI: retry flaky tests up to 2x
      openMode: 0,  // Interactive: no auto-retry (you see the failure immediately)
    },

    // ── Screenshot / Video ──────────────────────────────────────────────
    screenshotOnRunFailure: true,
    video: true,
    videosFolder: "cypress/videos",
    screenshotsFolder: "cypress/screenshots",

    // ── Reporter: Mochawesome HTML dashboard ────────────────────────────
    reporter: "../../node_modules/mochawesome",
    reporterOptions: {
      reportDir: "cypress/reports",
      overwrite: false,
      html: false,   // generated by mochawesome-merge in the npm script
      json: true,
      timestamp: "isoDateTime",
    },

    setupNodeEvents(on, config) {
      // Task: read credentials from cypress.env.json at runtime
      on("task", {
        log(message: string) {
          console.log(message);
          return null;
        },
      });
      return config;
    },
  },
});
