/**
 * Bridge's full occupation code reference — pulled directly from their own
 * `GET /v0/lists/occupation_codes` endpoint (confirmed live 2026-09-06;
 * Bridge support pointed to this as the canonical source rather than
 * reverse-engineering it from a validation error's enum list, which is how
 * an earlier, much smaller hand-curated version of this file was built).
 * Every code/label pair below is Bridge's own `display_name`, title-cased
 * for display and sorted alphabetically — not derived from the O*NET/SOC
 * standard ourselves. Three known formatting artifacts in Bridge's raw
 * response (lost separators/spaces on codes 499098, 519198, 999999) are
 * patched here; everything else is theirs verbatim.
 *
 * 570 of Bridge's ~571 accepted `most_recent_occupation` values are
 * covered (the one omission, "999998", isn't in Bridge's own reference
 * list either) — OccupationPicker's manual-entry fallback exists only as
 * insurance against Bridge adding new codes this static list hasn't
 * picked up yet.
 */
export const OCCUPATION_CODES: { code: string; label: string }[] = [
    { code: "132011", label: "Accountant and Auditor" },
    { code: "272011", label: "Actor" },
    { code: "152011", label: "Actuary" },
    { code: "291291", label: "Acupuncturist" },
    { code: "519191", label: "Adhesive Bonding Machine Operator and Tender" },
    { code: "113012", label: "Administrative Services Manager" },
    { code: "112011", label: "Advertising and Promotions Manager" },
    { code: "413011", label: "Advertising Sales Agent" },
    { code: "172011", label: "Aerospace Engineer" },
    { code: "131011", label: "Agent and Business Manager of Artists Performers and Athletes" },
    { code: "194010", label: "Agricultural and Food Science Technician" },
    { code: "191010", label: "Agricultural and Food Scientist" },
    { code: "172021", label: "Agricultural Engineer" },
    { code: "452011", label: "Agricultural Inspector" },
    { code: "532020", label: "Air Traffic Controller and Airfield Operations Specialist" },
    { code: "493011", label: "Aircraft Mechanic and Service Technician" },
    { code: "532010", label: "Aircraft Pilots and Flight Engineer" },
    { code: "512011", label: "Aircraft Structure Surfaces Rigging and Systems Assembler" },
    { code: "533011", label: "Ambulance Driver and Attendant except Emergency Medical Technician" },
    { code: "452021", label: "Animal Breeder" },
    { code: "392021", label: "Animal Caretaker" },
    { code: "339011", label: "Animal Control Worker" },
    { code: "392011", label: "Animal Trainer" },
    { code: "171011", label: "Architect except Landscape and Naval" },
    { code: "173011", label: "Architectural and Civil Drafter" },
    { code: "119041", label: "Architectural and Engineering Manager" },
    { code: "254010", label: "Archivist Curator and Museum Technician" },
    { code: "271010", label: "Artist and Related Worker" },
    { code: "192010", label: "Astronomer and Physicist" },
    { code: "272021", label: "Athletes and Sports Competitor" },
    { code: "192021", label: "Atmospheric and Space Scientist" },
    { code: "291181", label: "Audiologist" },
    { code: "492097", label: "Audiovisual Equipment Installer and Repairer" },
    { code: "493021", label: "Automotive Body and Related Repairer" },
    { code: "493022", label: "Automotive Glass Installer and Repairer" },
    { code: "493023", label: "Automotive Service Technician and Mechanic" },
    { code: "492091", label: "Avionics Technician" },
    { code: "396010", label: "Baggage Porter Bellhop and Concierge" },
    { code: "333011", label: "Bailiff" },
    { code: "513011", label: "Baker" },
    { code: "395011", label: "Barber" },
    { code: "353011", label: "Bartender" },
    { code: "433011", label: "Bill and Account Collector" },
    { code: "433021", label: "Billing and Posting Clerk" },
    { code: "172031", label: "Bioengineer and Biomedical Engineer" },
    { code: "191020", label: "Biological Scientist" },
    { code: "194021", label: "Biological Technician" },
    { code: "472011", label: "Boilermaker" },
    { code: "433031", label: "Bookkeeping Accounting and Auditing Clerk" },
    { code: "472020", label: "Brickmason Blockmason and Stonemason" },
    { code: "273011", label: "Broadcast Announcer and Radio Disc Jockey" },
    { code: "274010", label: "Broadcast Sound and Lighting Technician" },
    { code: "434011", label: "Brokerage Clerk" },
    { code: "132031", label: "Budget Analyst" },
    { code: "493031", label: "Bus and Truck Mechanic and Diesel Engine Specialist" },
    { code: "131199", label: "Business Operations Specialist Other" },
    { code: "513020", label: "Butcher and Other Meat Poultry and Fish Processing Worker" },
    { code: "131021", label: "Buyer and Purchasing Agent Farm Products" },
    { code: "517011", label: "Cabinetmaker and Bench Carpenter" },
    { code: "292031", label: "Cardiovascular Technologist and Technician" },
    { code: "435011", label: "Cargo and Freight Agent" },
    { code: "472031", label: "Carpenter" },
    { code: "472040", label: "Carpet Floor and Tile Installer and Finisher" },
    { code: "412010", label: "Cashier" },
    { code: "472050", label: "Cement Mason Concrete Finisher and Terrazzo Worker" },
    { code: "351011", label: "Chef and Head Cook" },
    { code: "172041", label: "Chemical Engineer" },
    { code: "519010", label: "Chemical Processing Machine Setter Operator and Tender" },
    { code: "194031", label: "Chemical Technician" },
    { code: "192030", label: "Chemist and Materials Scientist" },
    { code: "111011", label: "Chief Executive" },
    { code: "211021", label: "Child Family and School Social Worker" },
    { code: "399011", label: "Childcare Worker" },
    { code: "291011", label: "Chiropractor" },
    { code: "172051", label: "Civil Engineer" },
    { code: "131030", label: "Claims Adjuster Appraiser Examiner and Investigator" },
    { code: "537061", label: "Cleaner of Vehicles and Equipment" },
    { code: "212011", label: "Clergy" },
    { code: "193033", label: "Clinical and Counseling Psychologist" },
    { code: "292010", label: "Clinical Laboratory Technologist and Technician" },
    { code: "272022", label: "Coaches and Scout" },
    { code: "499091", label: "Coin Vending and Amusement Machine Servicer and Repairer" },
    { code: "271021", label: "Commercial and Industrial Designer" },
    { code: "499092", label: "Commercial Diver" },
    { code: "432099", label: "Communications Equipment Operator Other" },
    { code: "113111", label: "Compensation and Benefits Manager" },
    { code: "131141", label: "Compensation Benefits and Job Analysis Specialist" },
    { code: "131041", label: "Compliance Officer" },
    { code: "151221", label: "Computer and Information Research Scientist" },
    { code: "113021", label: "Computer and Information Systems Manager" },
    { code: "492011", label: "Computer Automated Teller and Office Machine Repairer" },
    { code: "172061", label: "Computer Hardware Engineer" },
    { code: "151241", label: "Computer Network Architect" },
    { code: "519160", label: "Computer Numerically Controlled Tool Operator and Programmer" },
    { code: "151299", label: "Computer Occupation Other" },
    { code: "151251", label: "Computer Programmer" },
    { code: "151230", label: "Computer Support Specialist" },
    { code: "151211", label: "Computer Systems Analyst" },
    { code: "191030", label: "Conservation Scientist and Forester" },
    { code: "474011", label: "Construction and Building Inspector" },
    { code: "472070", label: "Construction Equipment Operator" },
    { code: "472061", label: "Construction Laborer" },
    { code: "119021", label: "Construction Manager" },
    { code: "499010", label: "Control and Valve Installer and Repairer" },
    { code: "5370XX", label: "Conveyor Dredge and Hoist and Winch Operator" },
    { code: "352010", label: "Cook" },
    { code: "333012", label: "Correctional Officer and Jailer" },
    { code: "434021", label: "Correspondence Clerk" },
    { code: "131051", label: "Cost Estimator" },
    { code: "211019", label: "Counselor Other" },
    { code: "412021", label: "Counter and Rental Clerk" },
    { code: "435021", label: "Courier and Messenger" },
    { code: "434031", label: "Court Municipal and License Clerk" },
    { code: "273092", label: "Court Reporter and Simultaneous Captioner" },
    { code: "537021", label: "Crane and Tower Operator" },
    { code: "132041", label: "Credit Analyst" },
    { code: "434041", label: "Credit Authorizer Checker and Clerk" },
    { code: "132070", label: "Credit Counselor and Loan Officer" },
    { code: "339091", label: "Crossing Guard and Flagger" },
    { code: "519020", label: "Crushing Grinding Polishing Mixing and Blending Worker" },
    { code: "434051", label: "Customer Service Representative" },
    { code: "514031", label: "Cutting Punching and Press Machine Setter Operator and Tender Metal and Plastic" },
    { code: "519030", label: "Cutting Worker" },
    { code: "272030", label: "Dancer and Choreographer" },
    { code: "439021", label: "Data Labeler and Data Entry Keyer" },
    { code: "15124X", label: "Database Administrator and Architect" },
    { code: "519080", label: "Dental and Ophthalmic Laboratory Technician and Medical Appliance Technician" },
    { code: "319091", label: "Dental Assistant" },
    { code: "291292", label: "Dental Hygienist" },
    { code: "291020", label: "Dentist" },
    { code: "475010", label: "Derrick Rotary Drill and Service Unit Operator Oil and Gas" },
    { code: "439031", label: "Desktop Publisher" },
    { code: "333021", label: "Detective and Criminal Investigator" },
    { code: "292032", label: "Diagnostic Medical Sonographer" },
    { code: "29205X", label: "Dietetic Technician and Ophthalmic Medical Technician" },
    { code: "291031", label: "Dietitian and Nutritionist" },
    { code: "359011", label: "Dining Room and Cafeteria Attendant and Bartender Helper" },
    { code: "212021", label: "Director Religious Activities and Educatio" },
    { code: "272091", label: "Disc Jockey except Radio" },
    { code: "359021", label: "Dishwasher" },
    { code: "435032", label: "Dispatcher except Police Fire and Ambulance" },
    { code: "419091", label: "Doortodoor Sales Worker News and Street Vendor and Related Worker" },
    { code: "533030", label: "Driversales Worker and Truck Driver" },
    { code: "472080", label: "Drywall Installer Ceiling Tile Installer and Taper" },
    { code: "475023", label: "Earth Driller except Oil and Gas" },
    { code: "193011", label: "Economist" },
    { code: "273041", label: "Editor" },
    { code: "119030", label: "Education and Childcare Administrator" },
    { code: "211012", label: "Educational Guidance and Career Counselor and Advisor" },
    { code: "492092", label: "Electric Motor Power Tool and Related Repairer" },
    { code: "173023", label: "Electrical and Electronic Engineering Technologist and Technician" },
    { code: "172070", label: "Electrical and Electronics Engineer" },
    { code: "492093", label: "Electrical and Electronics Installer and Repairer Transportation Equipment" },
    { code: "49209X", label: "Electrical and Electronics Repairer Industrial and Utility" },
    { code: "512020", label: "Electrical Electronics and Electromechanical Assembler" },
    { code: "499051", label: "Electrical Powerline Installer and Repairer" },
    { code: "472111", label: "Electrician" },
    { code: "492096", label: "Electronic Equipment Installer and Repairer Motor Vehicles" },
    { code: "252020", label: "Elementary and Middle School Teacher" },
    { code: "474021", label: "Elevator and Escalator Installer and Repairer" },
    { code: "434061", label: "Eligibility Interviewer Government Programs" },
    { code: "3940XX", label: "Embalmer Crematory Operator and Funeral Attendant" },
    { code: "119161", label: "Emergency Management Director" },
    { code: "292042", label: "Emergency Medical Technician" },
    { code: "291214", label: "Emergency Medicine Physician" },
    { code: "512031", label: "Engine and Other Machine Assembler" },
    { code: "172199", label: "Engineer Other" },
    { code: "272099", label: "Entertainer and Performer Sports and Related Worker Other" },
    { code: "119070", label: "Entertainment and Recreation Manager" },
    { code: "172081", label: "Environmental Engineer" },
    { code: "194040", label: "Environmental Science and Geoscience Technician" },
    { code: "192041", label: "Environmental Scientist and Specialist Including Health" },
    { code: "519194", label: "Etcher and Engraver" },
    { code: "475022", label: "Excavating and Loading Machine and Dragline Operator Surface Mining" },
    { code: "436011", label: "Executive Secretary and Executive Administrative Assistant" },
    { code: "291128", label: "Exercise Physiologist" },
    { code: "399031", label: "Exercise Trainer and Group Fitness Instructor" },
    { code: "475032", label: "Explosives Worker Ordnance Handling Expert and Blaster" },
    { code: "519041", label: "Extruding Forming Pressing and Compacting Machine Setter Operator and Tender" },
    { code: "113013", label: "Facilities Manager" },
    { code: "119013", label: "Farmer Rancher and Other Agricultural Manager" },
    { code: "271022", label: "Fashion Designer" },
    { code: "353023", label: "Fast Food and Counter Worker" },
    { code: "474031", label: "Fence Erector" },
    { code: "434071", label: "File Clerk" },
    { code: "132051", label: "Financial and Investment Analyst" },
    { code: "433099", label: "Financial Clerk Other" },
    { code: "132061", label: "Financial Examiner" },
    { code: "113031", label: "Financial Manager" },
    { code: "332020", label: "Fire Inspector" },
    { code: "332011", label: "Firefighter" },
    { code: "552010", label: "Firstline Enlisted Military Supervisor" },
    { code: "471011", label: "Firstline Supervisor of Construction Trades and Extraction Worker" },
    { code: "331011", label: "Firstline Supervisor of Correctional Officer" },
    { code: "451011", label: "Firstline Supervisor of Farming Fishing and Forestry Worker" },
    { code: "331021", label: "Firstline Supervisor of Firefighting and Prevention Worker" },
    { code: "351012", label: "Firstline Supervisor of Food Preparation and Serving Workers" },
    { code: "371011", label: "Firstline Supervisor of Housekeeping and Janitorial Workers" },
    { code: "371012", label: "Firstline Supervisor of Landscaping Lawn Service and Groundskeeping Workers" },
    { code: "491011", label: "Firstline Supervisor of Mechanics Installers and Repairers" },
    { code: "411012", label: "Firstline Supervisor of Nonretail Sales Workers" },
    { code: "431011", label: "Firstline Supervisor of Office and Administrative Support Workers" },
    { code: "331012", label: "Firstline Supervisor of Police and Detective" },
    { code: "511011", label: "Firstline Supervisor of Production and Operating Worker" },
    { code: "331099", label: "Firstline Supervisor of Protective Service Worker Other" },
    { code: "411011", label: "Firstline Supervisor of Retail Sales Workers" },
    { code: "331091", label: "Firstline Supervisor of Security Worker" },
    { code: "333031", label: "Fish and Game Warden" },
    { code: "453031", label: "Fishing and Hunting Worker" },
    { code: "532031", label: "Flight Attendant" },
    { code: "271023", label: "Floral Designer" },
    { code: "513091", label: "Food and Tobacco Roasting Baking and Drying Machine Operator and Tender" },
    { code: "513092", label: "Food Batchmaker" },
    { code: "513093", label: "Food Cooking Machine Operator and Tender" },
    { code: "359099", label: "Food Preparation and Serving Related Worker Other" },
    { code: "352021", label: "Food Preparation Worker" },
    { code: "513099", label: "Food Processing Worker Other" },
    { code: "353041", label: "Food Server Nonrestaurant" },
    { code: "119051", label: "Food Service Manager" },
    { code: "454011", label: "Forest and Conservation Worker" },
    { code: "514020", label: "Forming Machine Setter Operator and Tender Metal and Plastic" },
    { code: "131131", label: "Fundraiser" },
    { code: "119171", label: "Funeral Home Manager" },
    { code: "519051", label: "Furnace Kiln Oven Drier and Kettle Operator and Tender" },
    { code: "517021", label: "Furniture Finisher" },
    { code: "433041", label: "Gambling Cage Worker" },
    { code: "393010", label: "Gambling Services Worker" },
    { code: "111021", label: "General and Operations Manager" },
    { code: "19204X", label: "Geoscientist and Hydrologist except Geographer" },
    { code: "472121", label: "Glazier" },
    { code: "452041", label: "Grader and Sorter Agricultural Product" },
    { code: "271024", label: "Graphic Designer" },
    { code: "514033", label: "Grinding Lapping Polishing and Buffing Machine Tool Setter Operator and Tender Metal and Plastic" },
    { code: "395012", label: "Hairdresser Hairstylist and Cosmetologist" },
    { code: "474041", label: "Hazardous Materials Removal Worker" },
    { code: "291299", label: "Healthcare Diagnosing or Treating Practitioner Other" },
    { code: "211022", label: "Healthcare Social Worker" },
    { code: "499021", label: "Heating Air Conditioning and Refrigeration Mechanic and Installer" },
    { code: "493040", label: "Heavy Vehicle and Mobile Equipment Service Technician and Mechanic" },
    { code: "473010", label: "Helper Construction Trade" },
    { code: "499098", label: "Helper, Installation Maintenance and Repair Worker" },
    { code: "519198", label: "Helper, Production Worker" },
    { code: "474051", label: "Highway Maintenance Worker" },
    { code: "499031", label: "Home Appliance Repairer" },
    { code: "311121", label: "Home Health Aide" },
    { code: "359031", label: "Host and Hostess Restaurant Lounge and Coffee Shop" },
    { code: "434081", label: "Hotel Motel and Resort Desk Clerk" },
    { code: "434161", label: "Human Resources Assistant except Payroll and Timekeeping" },
    { code: "113121", label: "Human Resources Manager" },
    { code: "131070", label: "Human Resources Worker" },
    { code: "49904X", label: "Industrial and Refractory Machinery Mechanic" },
    { code: "172110", label: "Industrial Engineer Including Health and Safety" },
    { code: "113051", label: "Industrial Production Manager" },
    { code: "537051", label: "Industrial Truck and Tractor Operator" },
    { code: "434199", label: "Information and Record Clerk Other" },
    { code: "151212", label: "Information Security Analyst" },
    { code: "519061", label: "Inspector Tester Sorter Sampler and Weigher" },
    { code: "472130", label: "Insulation Worker" },
    { code: "439041", label: "Insurance Claims and Policy Processing Clerk" },
    { code: "413021", label: "Insurance Sales Agent" },
    { code: "132053", label: "Insurance Underwriter" },
    { code: "271025", label: "Interior Designer" },
    { code: "273091", label: "Interpreter and Translator" },
    { code: "434111", label: "Interviewer except Eligibility and Loan" },
    { code: "523910", label: "Investor or Trader" },
    { code: "37201X", label: "Janitor and Building Cleaner" },
    { code: "519071", label: "Jeweler and Precious Stone and Metal Worker" },
    { code: "231020", label: "Judge Magistrate and Other Judicial Worker" },
    { code: "231012", label: "Judicial Law Clerk" },
    { code: "537062", label: "Laborer and Freight Stock and Material Mover Hand" },
    { code: "171012", label: "Landscape Architect" },
    { code: "373011", label: "Landscaping and Groundskeeping Worker" },
    { code: "516011", label: "Laundry and Drycleaning Worker" },
    { code: "231011", label: "Lawyer" },
    { code: "436012", label: "Legal Secretary and Administrative Assistant" },
    { code: "232099", label: "Legal Support Worker Other" },
    { code: "111031", label: "Legislator" },
    { code: "254022", label: "Librarian and Media Collections Specialist" },
    { code: "434121", label: "Library Assistant Clerical" },
    { code: "254031", label: "Library Technician" },
    { code: "292061", label: "Licensed Practical and Licensed Vocational Nurse" },
    { code: "191099", label: "Life Scientist Other" },
    { code: "434131", label: "Loan Interviewer and Clerk" },
    { code: "499094", label: "Locksmith and Safe Repairer" },
    { code: "534010", label: "Locomotive Engineer and Operator" },
    { code: "119081", label: "Lodging Manager" },
    { code: "454020", label: "Logging Worker" },
    { code: "131081", label: "Logistician" },
    { code: "537063", label: "Machine Feeder and Offbearer" },
    { code: "514041", label: "Machinist" },
    { code: "292035", label: "Magnetic Resonance Imaging Technologist" },
    { code: "372012", label: "Maids and Housekeeping Cleaner" },
    { code: "439051", label: "Mail Clerk and Mail Machine Operator except Postal Service" },
    { code: "499071", label: "Maintenance and Repair Worker General" },
    { code: "499043", label: "Maintenance Worker Machinery" },
    { code: "131111", label: "Management Analyst" },
    { code: "119199", label: "Manager Other" },
    { code: "395092", label: "Manicurist and Pedicurist" },
    { code: "499095", label: "Manufactured Building and Mobile Home Installer" },
    { code: "172121", label: "Marine Engineer and Naval Architect" },
    { code: "131161", label: "Market Research Analyst and Marketing Specialist" },
    { code: "112021", label: "Marketing Manager" },
    { code: "211013", label: "Marriage and Family Therapist" },
    { code: "319011", label: "Massage Therapist" },
    { code: "172131", label: "Materials Engineer" },
    { code: "152021", label: "Mathematician" },
    { code: "172141", label: "Mechanical Engineer" },
    { code: "274099", label: "Media and Communication Equipment Worker Other" },
    { code: "273099", label: "Media and Communication Worker Other" },
    { code: "119111", label: "Medical and Health Services Manager" },
    { code: "319092", label: "Medical Assistant" },
    { code: "292072", label: "Medical Records Specialist" },
    { code: "191040", label: "Medical Scientist" },
    { code: "436013", label: "Medical Secretary and Administrative Assistant" },
    { code: "319094", label: "Medical Transcriptionist" },
    { code: "131121", label: "Meeting Convention and Event Planner" },
    { code: "211023", label: "Mental Health and Substance Abuse Social Worker" },
    { code: "211014", label: "Mental Health Counselor" },
    { code: "271026", label: "Merchandise Displayer and Window Trimmer" },
    { code: "514050", label: "Metal Furnace Operator Tender Pourer and Caster" },
    { code: "435041", label: "Meter Reader Utilities" },
    { code: "553010", label: "Military Enlisted Tactical Operations and Airweapons Specialist and Crew Member" },
    { code: "551010", label: "Military Officer Special and Tactical Operations Leader" },
    { code: "554010", label: "Military Rank Not Specified" },
    { code: "499044", label: "Millwright" },
    { code: "172151", label: "Mining and Geological Engineer Including Mining Safety Engineer" },
    { code: "452090", label: "Miscellaneous Agricultural Worker" },
    { code: "474090", label: "Miscellaneous Construction and Related Worker" },
    { code: "292090", label: "Miscellaneous Health Technologist and Technician" },
    { code: "518090", label: "Miscellaneous Plant and System Operator" },
    { code: "193090", label: "Miscellaneous Social Scientist and Related Worker" },
    { code: "493090", label: "Miscellaneous Vehicle and Mobile Equipment Mechanic Installer and Repairer" },
    { code: "419010", label: "Model Demonstrator and Product Promoter" },
    { code: "514060", label: "Model Maker and Patternmaker Metal and Plastic" },
    { code: "514070", label: "Molder and Molding Machine Setter Operator and Tender Metal and Plastic" },
    { code: "519195", label: "Molder Shaper and Caster except Metal and Plastic" },
    { code: "394031", label: "Mortician Undertaker and Funeral Arranger" },
    { code: "533099", label: "Motor Vehicle Operator Other" },
    { code: "272041", label: "Music Director and Composer" },
    { code: "272042", label: "Musician and Singer" },
    { code: "119121", label: "Natural Sciences Manager" },
    { code: "151244", label: "Network and Computer Systems Administrator" },
    { code: "434141", label: "New Accounts Clerk" },
    { code: "273023", label: "News Analyst Reporter and Journalist" },
    { code: "172161", label: "Nuclear Engineer" },
    { code: "29203X", label: "Nuclear Medicine Technologist and Medical Dosimetrist" },
    { code: "194051", label: "Nuclear Technician" },
    { code: "291151", label: "Nurse Anesthetist" },
    { code: "291161", label: "Nurse Midwife" },
    { code: "291171", label: "Nurse Practitioner" },
    { code: "311131", label: "Nursing Assistant" },
    { code: "195010", label: "Occupational Health and Safety Specialist and Technician" },
    { code: "291122", label: "Occupational Therapist" },
    { code: "312010", label: "Occupational Therapy Assistant and Aide" },
    { code: "439199", label: "Office and Administrative Support Worker Other" },
    { code: "439061", label: "Office Clerk General" },
    { code: "439071", label: "Office Machine Operator except Computer" },
    { code: "152031", label: "Operations Research Analyst" },
    { code: "292081", label: "Optician Dispensing" },
    { code: "291041", label: "Optometrist" },
    { code: "434151", label: "Order Clerk" },
    { code: "31113X", label: "Orderly and Psychiatric Aide" },
    { code: "5120XX", label: "Other Assembler and Fabricator" },
    { code: "21109X", label: "Other Community and Social Service Specialist" },
    { code: "27102X", label: "Other Designer" },
    { code: "17301X", label: "Other Drafter" },
    { code: "2590XX", label: "Other Educational Instruction and Library Worker" },
    { code: "17302X", label: "Other Engineering Technologist and Technician" },
    { code: "3930XX", label: "Other Entertainment Attendant and Related Worker" },
    { code: "4750XX", label: "Other Extraction Worker" },
    { code: "1320XX", label: "Other Financial Specialist" },
    { code: "37301X", label: "Other Grounds Maintenance Worker" },
    { code: "299000", label: "Other Healthcare Practitioner and Technical Occupation" },
    { code: "31909X", label: "Other Healthcare Support Worker" },
    { code: "49909X", label: "Other Installation Maintenance and Repair Worker" },
    { code: "1940XX", label: "Other Life Physical and Social Science Technician" },
    { code: "51403X", label: "Other Machine Tool Setter Operator and Tender Metal and Plastic" },
    { code: "5371XX", label: "Other Material Moving Worker" },
    { code: "1520XX", label: "Other Mathematical Science Occupation" },
    { code: "514XXX", label: "Other Metal Worker and Plastic Worker" },
    { code: "39509X", label: "Other Personal Appearance Worker" },
    { code: "2912XX", label: "Other Physician" },
    { code: "51919X", label: "Other Production Equipment Operator and Tender" },
    { code: "5191XX", label: "Other Production Worker" },
    { code: "33909X", label: "Other Protective Service Worker" },
    { code: "19303X", label: "Other Psychologist" },
    { code: "5340XX", label: "Other Rail Transportation Worker" },
    { code: "2530XX", label: "Other Teacher and Instructor" },
    { code: "51609X", label: "Other Textile Apparel and Furnishings Worker" },
    { code: "5360XX", label: "Other Transportation Worker" },
    { code: "5170XX", label: "Other Woodworker" },
    { code: "519111", label: "Packaging and Filling Machine Operator and Tender" },
    { code: "537064", label: "Packer and Packager Hand" },
    { code: "472140", label: "Painter and Paperhanger" },
    { code: "519120", label: "Painting Worker" },
    { code: "519196", label: "Paper Goods Machine Setter Operator and Tender" },
    { code: "232011", label: "Paralegal and Legal Assistant" },
    { code: "292043", label: "Paramedic" },
    { code: "536021", label: "Parking Attendant" },
    { code: "333041", label: "Parking Enforcement Worker" },
    { code: "412022", label: "Parts Salesperson" },
    { code: "536061", label: "Passenger Attendant" },
    { code: "433051", label: "Payroll and Timekeeping Clerk" },
    { code: "399099", label: "Personal Care and Service Worker Other" },
    { code: "132052", label: "Personal Financial Advisor" },
    { code: "119179", label: "Personal Service Manager Other" },
    { code: "372021", label: "Pest Control Worker" },
    { code: "172171", label: "Petroleum Engineer" },
    { code: "291051", label: "Pharmacist" },
    { code: "319095", label: "Pharmacy Aide" },
    { code: "292052", label: "Pharmacy Technician" },
    { code: "319097", label: "Phlebotomist" },
    { code: "274021", label: "Photographer" },
    { code: "519151", label: "Photographic Process Worker and Processing Machine Operator" },
    { code: "192099", label: "Physical Scientist Other" },
    { code: "291123", label: "Physical Therapist" },
    { code: "312020", label: "Physical Therapist Assistant and Aide" },
    { code: "291071", label: "Physician Assistant" },
    { code: "472151", label: "Pipelayer" },
    { code: "472161", label: "Plasterer and Stucco Mason" },
    { code: "472152", label: "Plumber Pipefitter and Steamfitter" },
    { code: "291081", label: "Podiatrist" },
    { code: "333050", label: "Police Officer" },
    { code: "435051", label: "Postal Service Clerk" },
    { code: "435052", label: "Postal Service Mail Carrier" },
    { code: "435053", label: "Postal Service Mail Sorter Processor and Processing Machine Operator" },
    { code: "119131", label: "Postmaster and Mail Superintendent" },
    { code: "251000", label: "Postsecondary Teacher" },
    { code: "518010", label: "Power Plant Operator Distributor and Dispatcher" },
    { code: "499060", label: "Precision Instrument and Equipment Repairer" },
    { code: "515111", label: "Prepress Technician and Worker" },
    { code: "252010", label: "Preschool and Kindergarten Teacher" },
    { code: "516021", label: "Presser Textile Garment and Related Material" },
    { code: "515113", label: "Print Binding and Finishing Worker" },
    { code: "515112", label: "Printing Press Operator" },
    { code: "339021", label: "Private Detective and Investigator" },
    { code: "211092", label: "Probation Officer and Correctional Treatment Specialist" },
    { code: "433061", label: "Procurement Clerk" },
    { code: "272012", label: "Producer and Director" },
    { code: "435061", label: "Production Planning and Expediting Clerk" },
    { code: "131082", label: "Project Management Specialist" },
    { code: "439081", label: "Proofreader and Copy Marker" },
    { code: "132020", label: "Property Appraiser and Assessor" },
    { code: "119141", label: "Property Real Estate and Community Association Manager" },
    { code: "292053", label: "Psychiatric Technician" },
    { code: "112030", label: "Public Relations and Fundraising Manager" },
    { code: "273031", label: "Public Relations Specialist" },
    { code: "435031", label: "Public Safety Telecommunicator" },
    { code: "537070", label: "Pumping Station Operator" },
    { code: "131023", label: "Purchasing Agent except Wholesale Retail and Farm Products" },
    { code: "113061", label: "Purchasing Manager" },
    { code: "291124", label: "Radiation Therapist" },
    { code: "492020", label: "Radio and Telecommunications Equipment Installer and Repairer" },
    { code: "292034", label: "Radiologic Technologist and Technician" },
    { code: "291224", label: "Radiologist" },
    { code: "534031", label: "Railroad Conductor and Yardmaster" },
    { code: "474061", label: "Railtrack Laying and Maintenance Equipment Operator" },
    { code: "419020", label: "Real Estate Broker and Sales Agent" },
    { code: "434171", label: "Receptionist and Information Clerk" },
    { code: "399032", label: "Recreation Worker" },
    { code: "291125", label: "Recreational Therapist" },
    { code: "537081", label: "Refuse and Recyclable Material Collector" },
    { code: "291141", label: "Registered Nurse" },
    { code: "211015", label: "Rehabilitation Counselor" },
    { code: "472171", label: "Reinforcing Iron and Rebar Worker" },
    { code: "212099", label: "Religious Worker Other" },
    { code: "434181", label: "Reservation and Transportation Ticket Agent and Travel Clerk" },
    { code: "399041", label: "Residential Advisor" },
    { code: "291126", label: "Respiratory Therapist" },
    { code: "412031", label: "Retail Salesperson" },
    { code: "499096", label: "Rigger" },
    { code: "472181", label: "Roofer" },
    { code: "475071", label: "Roustabout Oil and Gas" },
    { code: "535011", label: "Sailor and Marine Oiler" },
    { code: "419099", label: "Sales and Related Worker Other" },
    { code: "419031", label: "Sales Engineer" },
    { code: "112022", label: "Sales Manager" },
    { code: "413091", label: "Sales Representative of Services except Advertising Insurance Financial Services and Travel" },
    { code: "414010", label: "Sales Representatives Wholesale and Manufacturing" },
    { code: "517041", label: "Sawing Machine Setter Operator and Tender Wood" },
    { code: "533051", label: "School Bus Driver" },
    { code: "339094", label: "School Bus Monitor" },
    { code: "193034", label: "School Psychologist" },
    { code: "252030", label: "Secondary School Teacher" },
    { code: "436014", label: "Secretary and Administrative Assistant except Legal Medical and Executive" },
    { code: "413031", label: "Securities Commodities and Financial Services Sales Agent" },
    { code: "492098", label: "Security and Fire Alarm Systems Installer" },
    { code: "339030", label: "Security Guard and Gambling Surveillance Officer" },
    { code: "474071", label: "Septic Tank Servicer and Sewer Pipe Cleaner" },
    { code: "516031", label: "Sewing Machine Operator" },
    { code: "472211", label: "Sheet Metal Worker" },
    { code: "535020", label: "Ship and Boat Captain and Operator" },
    { code: "535031", label: "Ship Engineer" },
    { code: "435071", label: "Shipping Receiving and Inventory Clerk" },
    { code: "516040", label: "Shoe and Leather Worker" },
    { code: "533053", label: "Shuttle Driver and Chauffeur" },
    { code: "395094", label: "Skincare Specialist" },
    { code: "493050", label: "Small Engine Mechanic" },
    { code: "119151", label: "Social and Community Service Manager" },
    { code: "211093", label: "Social and Human Service Assistant" },
    { code: "194061", label: "Social Science Research Assistant" },
    { code: "211029", label: "Social Worker Other" },
    { code: "193041", label: "Sociologist" },
    { code: "151252", label: "Software Developer" },
    { code: "151253", label: "Software Quality Assurance Analyst and Tester" },
    { code: "472231", label: "Solar Photovoltaic Installer" },
    { code: "252050", label: "Special Education Teacher" },
    { code: "291127", label: "Speechlanguage Pathologist" },
    { code: "518021", label: "Stationary Engineer and Boiler Operator" },
    { code: "439111", label: "Statistical Assistant" },
    { code: "152041", label: "Statistician" },
    { code: "537065", label: "Stocker and Order Filler" },
    { code: "472221", label: "Structural Iron and Steel Worker" },
    { code: "512041", label: "Structural Metal Fabricator and Fitter" },
    { code: "211011", label: "Substance Abuse and Behavioral Disorder Counselor" },
    { code: "391000", label: "Supervisor of Personal Care and Service Worker" },
    { code: "531000", label: "Supervisor of Transportation and Material Moving Worker" },
    { code: "291240", label: "Surgeon" },
    { code: "292055", label: "Surgical Technologist" },
    { code: "193022", label: "Survey Researcher" },
    { code: "173031", label: "Surveying and Mapping Technician" },
    { code: "171020", label: "Surveyor Cartographer and Photogrammetrist" },
    { code: "432011", label: "Switchboard Operator Including Answering Service" },
    { code: "516050", label: "Tailor Dressmaker and Sewer" },
    { code: "132081", label: "Tax Examiner and Collector and Revenue Agent" },
    { code: "132082", label: "Tax Preparer" },
    { code: "533054", label: "Taxi Driver" },
    { code: "259040", label: "Teaching Assistant" },
    { code: "273042", label: "Technical Writer" },
    { code: "499052", label: "Telecommunications Line Installer and Repairer" },
    { code: "419041", label: "Telemarketer" },
    { code: "432021", label: "Telephone Operator" },
    { code: "274030", label: "Television Video and Film Camera Operator and Editor" },
    { code: "433071", label: "Teller" },
    { code: "516060", label: "Textile Machine Setter Operator and Tender" },
    { code: "291129", label: "Therapist Other" },
    { code: "519197", label: "Tire Builder" },
    { code: "232093", label: "Title Examiner Abstractor and Searcher" },
    { code: "514111", label: "Tool and Die Maker" },
    { code: "397010", label: "Tour and Travel Guide" },
    { code: "113131", label: "Training and Development Manager" },
    { code: "131151", label: "Training and Development Specialist" },
    { code: "533052", label: "Transit and Intercity Bus Driver" },
    { code: "536051", label: "Transportation Inspector" },
    { code: "339093", label: "Transportation Security Screener" },
    { code: "536030", label: "Transportation Service Attendant" },
    { code: "113071", label: "Transportation Storage and Distribution Manager" },
    { code: "413041", label: "Travel Agent" },
    { code: "373013", label: "Tree Trimmer and Pruner" },
    { code: "253041", label: "Tutor" },
    { code: "272023", label: "Umpire Referee and Other Sports Official" },
    { code: "475040", label: "Underground Mining Machine Operator" },
    { code: "999999", label: "Unemployed with No Work Experience in the Last 5 Years or Earlier, or Never Worked" },
    { code: "516093", label: "Upholsterer" },
    { code: "193051", label: "Urban and Regional Planner" },
    { code: "393031", label: "Usher Lobby Attendant and Ticket Taker" },
    { code: "291131", label: "Veterinarian" },
    { code: "319096", label: "Veterinary Assistant and Laboratory Animal Caretaker" },
    { code: "292056", label: "Veterinary Technologist and Technician" },
    { code: "353031", label: "Waiter or Waitress" },
    { code: "518031", label: "Water and Wastewater Treatment Plant and System Operator" },
    { code: "151255", label: "Web and Digital Interface Designer" },
    { code: "151254", label: "Web Developer" },
    { code: "435111", label: "Weigher Measurer Checker and Sampler Recordkeeping" },
    { code: "514120", label: "Welding Soldering and Brazing Worker" },
    { code: "131022", label: "Wholesale and Retail Buyer except Farm Products" },
    { code: "499081", label: "Wind Turbine Service Technician" },
    { code: "517042", label: "Woodworking Machine Setter Operator and Tender except Sawing" },
    { code: "439022", label: "Word Processor and Typist" },
    { code: "273043", label: "Writer and Author" },
];
